PhilsNotes/PhilsNotes/urls.py
from django.conf.urls import url
from django.contrib import admin
from PhilsNotesApp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.joblist, name="joblist"),
    url(r'^jobnotes/(?P<job_id>\d+)/$', views.jobnotes, name="jobnotes"),
    url(r'^jobnotes/(?P<job_id>\d+)/savenote/$', views.savenote, name="savenote"),
    url(r'^jobedit/(?P<pk>\d+)/$', views.jobedit, name="jobedit"),
    url(r'^jobdelete/(?P<pk>\d+)', views.jobdelete, name="jobdelete"),
    url(r'^jobadd/$', views.jobadd, name="jobadd"),
    url(r'^builderadd/$', views.builder_add, name="builder_add"),
    url(r'^builderedit/(?P<pk>\d+)/$', views.builder_edit, name="builder_edit"),
    url(r'^builders/', views.builder_list, name='builder_list'),
    url(r'^builderdelete/(?P<pk>\d+)/$', views.builder_delete, name='builder_delete'),

]

PhilsNotes/PhilsNotesApp/models.py
from django.db import models


class Builder(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Builder"
        verbose_name_plural = "Builders"


class Job(models.Model):
    job_name = models.CharField(db_index=True, max_length=50)
    job_address = models.CharField(max_length=50, blank=True)
    job_city = models.CharField(max_length=50, blank=True)
    job_county = models.CharField(max_length=50, blank=True)
    builder = models.ForeignKey(Builder, blank=True, null=True)
    customer_name = models.CharField(db_index=True, max_length=100, blank=True)
    home_phone = models.CharField(max_length=20, blank=True)
    cell_phone = models.CharField(max_length=20, blank=True)
    cell_phone_2 = models.CharField(max_length=20, blank=True)
    work_phone = models.CharField(max_length=20, blank=True)
    email_1 = models.CharField(max_length=75, blank=True)
    email_2 = models.CharField(max_length=75, blank=True)

    def __str__(self):
        return self.job_name

    class Meta:
        verbose_name = "Job"
        verbose_name_plural = "Jobs"


class JobNote(models.Model):
    job = models.ForeignKey(Job)
    note_date = models.DateField(db_index=True)
    note_text = models.CharField(max_length=2048)  # just cuz it feels right to be actually 2K.

    def __str__(self):
        return str(self.job) + ': ' + str(self.note_date)

    class Meta:
        verbose_name = "Job Note"
        verbose_name_plural = "Job Notes"

PhilsNotes/PhilsNotesApp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Job, JobNote, Builder
import datetime


class DateInput(forms.DateInput):
    input_type = 'date'
    initial = datetime.date.today


class JobNoteForm(ModelForm):
    class Meta:
        model = JobNote
        fields = ['note_date', 'note_text']
        widgets = {
            'note_text': forms.Textarea(attrs={'rows': '3'}),
        }


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = '__all__'


class BuilderForm(ModelForm):
    class Meta:
        model = Builder
        fields = '__all__'

PhilsNotes/PhilsNotesApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from .models import Job, JobNote, Builder
from .forms import JobNoteForm, JobForm, BuilderForm


# Create your views here.
def joblist(request):
    # dump name sorted list of jobs
    jobs = Job.objects.all().order_by('job_name')
    return render(request, 'joblist.html', {'jobs': jobs})


def builder_list(request):
    builders = Builder.objects.all()
    return render(request, 'builderlist.html', {'builders': builders})


def jobnotes(request, job_id):
    # job = Job.objects.get(pk=job_id)
    job = get_object_or_404(Job, pk=job_id)
    jobnotes = JobNote.objects.filter(job=job).order_by('-note_date')

    noteform = JobNoteForm()

    return render(request, 'jobnotes.html', {'noteform': noteform, 'job': job, 'jobnotes': jobnotes})


def savenote(request, job_id):
    # get form data...  new stuff for me.. LOL

    if request.method == "POST":
        form = JobNoteForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.job_id = job_id
            model_instance.save()
            return redirect('/')


def jobedit(request, pk):
    job = get_object_or_404(Job, pk=pk)

    form = JobForm(request.POST or None, instance=job)

    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'jobform.html', {'jobform': form})


def builder_edit(request, pk):
    builder = get_object_or_404(Builder, pk=pk)

    form = BuilderForm(request.POST or None, instance=builder)

    if form.is_valid():
        form.save()
        return redirect('/builders/')

    return render(request, 'builderform.html', {'builderform': form})


def jobdelete(request, pk):
    job = get_object_or_404(Job, pk=pk)

    if request.method == 'POST':
        job.delete()
        return redirect('/')
    return render(request, 'jobdelete.html', {'object': job})


def builder_delete(request, pk):
    builder = get_object_or_404(Builder, pk=pk)
    if request.method == 'POST':
        builder.delete()
        return redirect('/builders/')
    return render(request, 'builderdelete.html', {'object': builder})


def jobadd(request, template_name='jobform.html'):
    form = JobForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, template_name, {'jobform': form})


def builder_add(request, template_name='builderform.html'):
    form = BuilderForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/builders/')
    return render(request, template_name, {'builderform': form})

PhilsNotes/PhilsNotesApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="assets/img/favicon.ico">
{% block styles %}
{% endblock %}

<title>Phil's Job Notes</title>

    <!-- BootSrap Core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!-- JQuery and JQueryUI -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<script>
{% block scripts %}
{% endblock %}
</script>
<!-- custom css inline, cuz, well, it's working for now. -->
<style>
    body { padding-top: 4rem;}
</style>

</head>
<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <a class="navbar-brand" href="#">Jobsite Notes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
          
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="/">Home/Jobs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/builders/">Builders</a>
                    </li>    
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </nav>

    <main role="main" class="container">
            {% block content %}
            {% endblock %}
    </main>   

</body>
</html>

PhilsNotes/PhilsNotesApp/templates/builderdelete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Builder: {{ object }}</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}"?<br><br>
    <input type="submit" value="Yes, Delete the Builder: {{ object }}" />
</form>
{% endblock %}

PhilsNotes/PhilsNotesApp/templates/builderform.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}

    {% for hidden_field in builderform.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}
  
    {% for field in builderform.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
  
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

PhilsNotes/PhilsNotesApp/templates/builderlist.html
{% extends 'base.html' %}

{% block content %}
<h1>Builders</h1>
<table class="table">
    <thead>
        <th>Builder</th>
        <th align="right"><a href="/builderadd"><i class="fas fa-plus"></i> Add Builder</a></th>
    </thead>
{% for builder in builders %}
    <tr>
        <td>{{ builder }}</td>
        <td align="right">
            <a href="/builderedit/{{ builder.id }}"><i class="fas fa-edit"></i></a>
            <a href="/builderdelete/{{ builder.id }}"><i class="fas fa-trash"></i></a>
        </td>
    </tr>
    
{% endfor %}
</table>

{% endblock %}

PhilsNotes/PhilsNotesApp/templates/jobdelete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Job: {{ object }}</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" and all it's notes?<br><br>
    <input type="submit" value="Yes, Delete the Job: {{ object }}" />
</form>
{% endblock %}

PhilsNotes/PhilsNotesApp/templates/jobform.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}

    {% for hidden_field in jobform.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}
  
    {% for field in jobform.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
  
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

PhilsNotes/PhilsNotesApp/templates/joblist.html
{% extends 'base.html' %}

{% block content %}
<h1>Job List</h1>
<table class="table">
    <thead>
        <th>Job Name</th>
        <th align="right"><a href="/jobadd"><i class="fas fa-plus"></i> Add Job</a></th>
    </thead>
{% for job in jobs %}
    <tr>
        <td><a href="/jobnotes/{{ job.id }}/">{{ job.job_name }}</a></td>
        <td align="right">
            <a href="/jobedit/{{ job.id }}"><i class="fas fa-edit"></i></a>
            <a href="/jobdelete/{{ job.id }}"><i class="fas fa-trash"></i></a>            
        </td>
    </tr>
    
{% endfor %}
</table>

{% endblock %}

PhilsNotes/PhilsNotesApp/templates/jobnotes.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block scripts %}

  $( function() {
    $( "#id_note_date" ).datepicker();

    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth()+1; //January is 0!
    var yyyy = today.getFullYear();

    if(dd<10) {
        dd = '0'+dd
    }

    if(mm<10) {
        mm = '0'+mm
    }

    today = mm + '/' + dd + '/' + yyyy;


    $( "#id_note_date" ).val(today);

  } );

{% endblock %}

{% block content %}
<h1>Notes: {{ job.job_name }}</h1>
<hr>
<form method="post" action="savenote/">
    {% csrf_token %}

    {% for hidden_field in noteform.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}
  
    {% for field in noteform.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
  
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

  <table class="table table-striped">
      <thead>
          <tr>
          <th scope="col">Date</th>
          <th scope="col">Note</th>
          </tr>
      </thead>
      <tbody>
        {% for note in jobnotes %}
        <tr>
            <td>{{ note.note_date }}</td>
            <td>{{ note.note_text }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>


{% endblock %}